import sys
import io
import re
import math

class PythonSandbox:
    """
    Executes Python code generated by the LLM safely(ish).
    """
    def execute(self, text: str) -> str:
        # Extract code from markdown blocks
        code_match = re.search(r"```python(.*?)```", text, re.DOTALL)
        if not code_match:
            return "" # No code found, not a tool call
        
        code = code_match.group(1).strip()
        
        # Capture standard output
        old_stdout = sys.stdout
        redirected_output = sys.stdout = io.StringIO()
        
        try:
            # simple safe globals
            exec_globals = {"math": math}
            exec(code, exec_globals)
            output = redirected_output.getvalue()
        except Exception as e:
            output = f"Runtime Error: {str(e)}"
        finally:
            sys.stdout = old_stdout
            
        return output.strip() or "[No Output]"